---
elasticsearch_version: 7x
elasticsearch_service_enabled: true
elasticsearch_network_host: localhost
elasticsearch_http_port: 9200
elasticsearch_jvm_heap_size_min: 1g
elasticsearch_jvm_heap_size_max: 1g
elasticsearch_home_dir: /usr/share/elasticsearch
elasticsearch_conf_dir: /etc/elasticsearch

