---
- name: Add Elasticsearch GPG key.
  ansible.builtin.rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository.
  ansible.builtin.template:
    src: RedHat/elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644

- name: Allow elasticsearch traffic through the firewall
  ansible.posix.firewalld:
    immediate: true
    permanent: true
    service: elasticsearch
    state: enabled