---
name: Build and Deploy Collection

on:
  push:

defaults:
  run:
    working-directory: 'zarrenspry.elastic'

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Deploy Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          entryPoint: 'zarrenspry.elastic'